title: The Cool Team Presents: PacManBot!!!
description: A RAS598 Mobile Robotics Project!
theme: just-the-docs

url: https://just-the-docs.github.io

remote_theme: just-the-docs/just-the-docs
math: mathjax

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
